from enum import Enum


class AnalysisStatus(str, Enum):
    SUCCESS = "SUCCESS"
    RETAKE_IMAGE = "RETAKE_IMAGE"
    AMBIGUOUS_RESULT = "AMBIGUOUS_RESULT"
    NO_MATCH_FOUND = "NO_MATCH_FOUND"
    INVALID_INCUBATION_TIME = "INVALID_INCUBATION_TIME"
    INVALID_IMAGE = "INVALID_IMAGE"
    UNSUPPORTED_TEST = "UNSUPPORTED_TEST"
    CALIBRATION_REQUIRED = "CALIBRATION_REQUIRED"
    ERROR = "ERROR"


class RejectionReason(str, Enum):
    BLURRY = "BLURRY"
    UNDEREXPOSED = "UNDEREXPOSED"
    OVEREXPOSED = "OVEREXPOSED"
    EXCESSIVE_REFLECTION = "EXCESSIVE_REFLECTION"
    BACKGROUND_CONTAMINATION = "BACKGROUND_CONTAMINATION"
    NON_UNIFORM_COLOR = "NON_UNIFORM_COLOR"
    INSUFFICIENT_VALID_PIXELS = "INSUFFICIENT_VALID_PIXELS"
    INVALID_RESOLUTION = "INVALID_RESOLUTION"
    CORRUPT_IMAGE = "CORRUPT_IMAGE"
    POOR_QUALITY_SCORE = "POOR_QUALITY_SCORE"
    INCUBATION_OUT_OF_BOUNDS = "INCUBATION_OUT_OF_BOUNDS"
    BOTTLE_NOT_DETECTED = "BOTTLE_NOT_DETECTED"
    LANDSCAPE_ORIENTATION = "LANDSCAPE_ORIENTATION"
    POOR_FRAMING_TOO_SMALL = "POOR_FRAMING_TOO_SMALL"
    POOR_FRAMING_TOO_LARGE = "POOR_FRAMING_TOO_LARGE"
    POOR_FRAMING_CLIPPED = "POOR_FRAMING_CLIPPED"
    COLORED_BACKGROUND = "COLORED_BACKGROUND"
    FLASH_DETECTED = "FLASH_DETECTED"
    BACKGROUND_TOO_DARK = "BACKGROUND_TOO_DARK"
    BACKGROUND_TOO_BRIGHT = "BACKGROUND_TOO_BRIGHT"


class CaptureProfile(str, Enum):
    SMARTPHONE_UNCONTROLLED_V1 = "SMARTPHONE_UNCONTROLLED_V1"
    CONTROLLED_BOX_V1 = "CONTROLLED_BOX_V1"


class WhiteBalanceMethod(str, Enum):
    NONE = "NONE"
    GRAY_WORLD = "GRAY_WORLD"
    SHADES_OF_GRAY = "SHADES_OF_GRAY"
    REFERENCE_PATCH = "REFERENCE_PATCH"
